spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  server:
    port: 8080
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect